ObisConcept:
  includeFrontendAssets: true
Neos:
  Neos:
    fusion:
      autoInclude:
        'ObisConcept.NeosSwiper': TRUE

    userInterface:
      translation:
        autoInclude:
          'ObisConcept.NeosSwiper': ['NodeTypes/*']
